
[dependencies]
tauri = { version = "1", features = ["api-all"] }
csv = "1.1"
tar = "0.4"
aws-sdk-s3 = { version = "0.0.25-alpha", features = ["rustls"] }
tokio = { version = "1", features = ["full"] }
