name: Build and Deploy Tauri App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js Dependencies
        run: yarn install

      - name: Build Frontend
        run: yarn build

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri App
        run: yarn tauri build

      - name: Upload Tauri Build
        uses: actions/upload-artifact@v2
        with:
          name: tauri-build
          path: src-tauri/target/release/bundle/
